### ISSUE TITLE
[ci] Setup travis, coveralls and requires.io

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-network-topolgy#3]
Setup travis, coveralls, requires.io and add badges to README

**Comment by rohithasrk** [comment]
@nemesisdesign Can you enable travis, coveralls, etc over this repo?

**Comment by nemesisdesign** [comment]
@rohithasrk will do

**Comment by nemesisdesign** [comment]
@rohithasrk done, at the next push the travis build will be triggered.

Add the badges in the README.

**Comment by rohithasrk** [comment]
@nemesisdesign Done.
